packages:
  - libs/*
  - plugins/*
  - apps/*

catalog:
  '@types/lodash-es': ^4.17.12
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  lodash-es: ^4.17.21
  react: ^19.2.0
  react-dom: ^19.2.0
  type-fest: ^4.31.0
